<<<<<<< HEAD
import { useRef, useContext } from "react";
import Wrapper from "../src/layout/Wrapper";
import { Scene1 } from "../src/scenes/Scene1";
import { Scene2 } from "../src/scenes/Scene2";
import { Scene3 } from "../src/scenes/Scene3";

import useIsomorphicLayoutEffect from "../src/animation/useIsomorphicLayoutEffect";
import { SmootherContext } from "../src/context/SmootherContext";

import gsap from "gsap-trial";
import { ScrollTrigger } from "gsap-trial/dist/ScrollTrigger";
import { ScrollToPlugin } from "gsap-trial/dist/ScrollToPlugin";

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

const IndexPage = () => {
  const smoother = useContext(SmootherContext);

  useIsomorphicLayoutEffect(() => {
    smoother && smoother.effects("[data-speed], [data-lag]", {});

    return () => {
      smoother && smoother.effects().forEach((t) => t.kill());
    };
  }, [smoother]);

  function scrollTo() {
    smoother && smoother.scrollTo("#scene4", true, "center center");
  }
=======
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

//Sections
import FirstSection from '../sections/1';
import SecondSection from '../sections/2';
import ThirdSection from '../sections/3';
import FourthSection from '../sections/4';

const inter = Inter({ subsets: ['latin'] })
>>>>>>> feat-last_sections

  return (
<<<<<<< HEAD
    <Wrapper
      url=""
      title="VenApp"
      description=""
      twitter=""
      imageUrl=""
      imageAlt=""
    >
      <div>
        <Scene1 />
        <Scene2 />
        <Scene3 />
      </div>
    </Wrapper>
  );
};

export default IndexPage;
=======
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <FourthSection />
      </main> 
    </>
  )
}
>>>>>>> feat-last_sections
